version: '3.8'

services:
  app:
    build: .
    container_name: auth_service__app
    env_file:
      - .env.production
    ports:
      - "${DOCKER_RUN_PORT:-5000}:${FLASK_RUN_PORT:-5000}"
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:${FLASK_RUN_PORT:-5000} wsgi:app